apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.microservice.name }}
---


apiVersion: apps/v1
kind: Deployment
metadata:
   name: dev-che
   labels:
      app: frontend
   namespace: {{ .Values.microservice.name }}
spec:
  replicas: 2
  matchLabels:
    app: frontend
  template:
    metadata:
      matchLabels:
        app: frontend
    spec:
        containers:
          - image: {{ .Values.microservice.images.names.backend.image }}
            name: {{ .Values.microservice.images.names.backend.name }}
            ports:
              containerPort: 8081
            env:
              - name: PORT_NUMBER:
                valueFrom:
                  configMapkeyRef:
                    name: port-number-CM
                    key: port_no

---
apiVersion: v1
kind: service
metadata:
  name: devche-frontendservice
  namesapce: {{ .Values.microservice.name }}
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
      app: frontend
    protocol: TCP
  type: LoadBalancer