apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.microservice.name }}
  labels:
     app: {{ .Values.microservice.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.microservice.name }}
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 60%
        maxSurge: 20%
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 75%