apiVersion: v1
kind: Service
metadata:
  name:{{ .Values.microservice.name }}
  labels:
    app: {{ .Values.microservice.name }}
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
   {{ .Values.microservice.name }}
