---
- hosts: microservice_APP
  gather_facts: no
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name:  Install the version latest version of package node and allow potential downgrades
      ansible.builtin.apt:
        name: nodejs
        state: present
      register: installing_the_node
      tags: provisioning
- hosts: microservice_APP
  gather_facts: no
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name:  Install the version latest version of package npm and allow potential downgrades
      ansible.builtin.apt:
        name: npm
        state: latest
      register: installing_the_npm
      tags: provisioning
- hosts: microservice_APP
  gather_facts: no
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name:  Install the latest version of package "maven" and allow potential downgrades
      ansible.builtin.apt:
        name: maven
        state: latest
      register: installing_the_maven
      tags: provisioning
- hosts: microservice_APP
  gather_facts: no
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name:  Install unzip
      ansible.builtin.apt:
        name: unzip
        state: present
      register: installing_the_unzip
      tags: provisioning        
- hosts: microservice_APP
  gather_facts: no
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: Download the JDK binaries
      ansible.builtin.get_url:
        url: https://download.oracle.com/java/17/archive/jdk-17.0.5_linux-x64_bin.tar.gz
        dest: /opt/jdk-17_linux-x64_bin.tar.gz
        mode: '0777'  
      tags: provisioning
    - name: Untar the downloaded file    
      ansible.builtin.unarchive:
        src: /opt/jdk-17_linux-x64_bin.tar.gz
        dest: /opt
        remote_src: yes
      tags: provisioning   
    - name: Set the JAVA_HOME in /etc/profile file
      ansible.builtin.lineinfile:
        path: /etc/profile
        state: present
        line: "{{ item }}"
      with_items:
            - 'export JAVA_HOME="/opt/jdk-17.0.5"'
            - 'export PATH=$PATH:$JAVA_HOME/bin'
      tags: provisioning    
- hosts: microservice_APP
  gather_facts: no
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: ./devcha-test-repo-main.zip
        dest: /tmp
        owner: root
        group: root
        mode: '0644'
      tags: provisioning
    - name: Unzip the downloaded file
      ansible.builtin.unarchive:
        src: /tmp/devcha-test-repo-main.zip
        dest: /tmp
        remote_src: yes
      tags: provisioning
- hosts: microservice_APP
  gather_facts: no
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: this block runs the maven with its goal
      ansible.builtin.command:
        cmd:  mvn package
        chdir: /tmp/devcha-test-repo-main/jumia_phone_validator/validator-backend
      tags: provisioning
- hosts: microservice_APP
  gather_facts: no
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: Download the JDK binaries
      apt:
         name: 
           - apt-transport-https
           - ca-certificates
           - curl
           - gnupg-agent
           - software-properties-common
         update_cache: yes
      tags: docker  
    - name: add apt-key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg 
      tags: docker
    - name: add docker repo
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
      tags: docker
    - name: install docker
      apt:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
        update_cache: yes
      tags: docker
    - name: add user permissions
      shell: "usermod -aG docker root" 
      tags: docker
    - name: install python package manager
      apt: 
        name: python3-pip
      tags: docker
    - name: install python sdk
      pip:
        name:
          - docker
          - docker-compose
      tags: docker     
